# Generated by Django 5.1.1 on 2024-09-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('delete_flag', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('product_id', models.BigIntegerField(verbose_name='商品id')),
                ('detail', models.JSONField(blank=True, null=True, verbose_name='商品详情')),
                ('param', models.JSONField(blank=True, null=True, verbose_name='商品参数')),
                ('rotation', models.JSONField(blank=True, null=True, verbose_name='轮播图片')),
            ],
            options={
                'verbose_name': '商品明细',
                'verbose_name_plural': '商品明细',
                'db_table': 'product_detail',
            },
        ),
    ]
