# Generated by Django 5.1.1 on 2024-09-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID')),
                ('create_user', models.IntegerField(default=0, verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间')),
                ('update_user', models.IntegerField(default=0, verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间')),
                ('delete_flag', models.BooleanField(default=0, verbose_name='逻辑删除')),
                ('parent_id', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='父id')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='名称')),
                ('status', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='启用禁用状态 1启用 0禁用')),
                ('sort_order', models.IntegerField(blank=True, default=0, null=True, verbose_name='排序')),
            ],
            options={
                'verbose_name': '类目',
                'verbose_name_plural': '类目',
                'db_table': 'category',
            },
        ),
    ]
