# Generated by Django 5.1.1 on 2024-09-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('order_no', models.CharField(default='', max_length=60, verbose_name='订单编号')),
                ('order_detail_no', models.CharField(default='', max_length=60, verbose_name='订单明细编号')),
                ('product_id', models.BigIntegerField(default=0, verbose_name='商品id')),
                ('product_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='商品名称')),
                ('status', models.SmallIntegerField(default=0, verbose_name='订单状态')),
                ('status_desc', models.CharField(blank=True, max_length=60, null=True, verbose_name='状态描述')),
            ],
            options={
                'verbose_name': '订单记录',
                'verbose_name_plural': '订单记录',
                'db_table': 'order_status_record',
            },
        ),
    ]
