# Generated by Django 5.1.1 on 2024-09-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='age',
        ),
        migrations.AddField(
            model_name='product',
            name='activity_id',
            field=models.BigIntegerField(null=True, verbose_name='活动id'),
        ),
        migrations.AddField(
            model_name='product',
            name='category_id',
            field=models.BigIntegerField(null=True, verbose_name='品类id'),
        ),
        migrations.AddField(
            model_name='product',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, max_length=11, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='create_user',
            field=models.IntegerField(default=0, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='product',
            name='delete_flag',
            field=models.BooleanField(default=0, verbose_name='逻辑删除'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='商品图片地址'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, verbose_name='商品单价'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_id',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='商品id'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='商品状态'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.IntegerField(default=0, verbose_name='库存数'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_images',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='子图片列表'),
        ),
        migrations.AddField(
            model_name='product',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='简要描述'),
        ),
        migrations.AddField(
            model_name='product',
            name='update_time',
            field=models.DateTimeField(auto_now=True, max_length=11, null=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='update_user',
            field=models.IntegerField(default=0, verbose_name='更新人'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='主键ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='商品名称'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
